/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputDate: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue')['default']
    UInputTime: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_a63e16831100c5a26a6d0d8d83127a44/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
